Rewritten to actually run the automated tests.
2007-03-24  Jeffrey Stedfast  <fejj@gnome.org>

	* Makefile.am (check-local): Rewritten to actually run the
	automated tests.

	* tests/test-mbox.c: Rewritten to use testsuite library.

	* tests/test-pgp.c: Rewritten to use testsuite library.

	* tests/test-pgpmime.c: Rewritten to use testsuite library.

	* tests/test-cat.c: Rewritten to use testsuite library.

	* tests/test-streams.c: Rewritten to use testsuite library.

	* tests/test-iconv.c: Rewritten to use testsuite library.

	* tests/testsuite.[c,h]: New automated test-suite helper library.


svn path=/trunk/; revision=1094

diff --git a/tests/Makefile.am b/tests/Makefile.am
--- a/tests/Makefile.am
+++ b/tests/Makefile.am
@@ -15,18 +15,22 @@ VERSION_FLAGS = -DGMIME_VERSION=\"$(GMIME_VERSION)\" 		\
 		-DGMIME_MINOR_VERSION=$(GMIME_MINOR_VERSION)	\
 		-DGMIME_MICRO_VERSION=$(GMIME_MICRO_VERSION)
 
-noinst_PROGRAMS = 	\
+AUTOMATED_TESTS =	\
+	test-iconv	\
+	test-streams	\
+	test-cat	\
+	test-mbox	\
+	test-pgp	\
+	test-pgpmime
+
+MANUAL_TESTS =		\
 	test-best	\
 	test-mime 	\
 	test-parser 	\
-	test-mbox 	\
-	test-streams 	\
-	test-cat	\
 	test-html 	\
-	test-iconv 	\
-	test-partial	\
-	test-pgp	\
-	test-pgpmime
+	test-partial
+
+noinst_PROGRAMS = $(AUTOMATED_TESTS) $(MANUAL_TESTS)
 
 DEPS = $(top_builddir)/gmime/libgmime-2.0.la
 LDADDS = $(top_builddir)/gmime/libgmime-2.0.la $(GLIB_LIBS)
@@ -46,17 +50,17 @@ test_parser_LDFLAGS =
 test_parser_DEPENDENCIES = $(DEPS)
 test_parser_LDADD = $(LDADDS)
 
-test_mbox_SOURCES = test-mbox.c
+test_mbox_SOURCES = test-mbox.c testsuite.c testsuite.h
 test_mbox_LDFLAGS = 
 test_mbox_DEPENDENCIES = $(DEPS)
 test_mbox_LDADD = $(LDADDS)
 
-test_streams_SOURCES = test-streams.c
+test_streams_SOURCES = test-streams.c testsuite.c testsuite.h
 test_streams_LDFLAGS = 
 test_streams_DEPENDENCIES = $(DEPS)
 test_streams_LDADD = $(LDADDS)
 
-test_cat_SOURCES = test-cat.c
+test_cat_SOURCES = test-cat.c testsuite.c testsuite.h
 test_cat_LDFLAGS = 
 test_cat_DEPENDENCIES = $(DEPS)
 test_cat_LDADD = $(LDADDS)
@@ -66,7 +70,7 @@ test_html_LDFLAGS =
 test_html_DEPENDENCIES = $(DEPS)
 test_html_LDADD = $(LDADDS)
 
-test_iconv_SOURCES = test-iconv.c
+test_iconv_SOURCES = test-iconv.c testsuite.c testsuite.h
 test_iconv_LDFLAGS = 
 test_iconv_DEPENDENCIES = $(DEPS)
 test_iconv_LDADD = $(LDADDS)
@@ -76,55 +80,47 @@ test_partial_LDFLAGS =
 test_partial_DEPENDENCIES = $(DEPS)
 test_partial_LDADD = $(LDADDS)
 
-test_pgp_SOURCES = test-pgp.c
+test_pgp_SOURCES = test-pgp.c testsuite.c testsuite.h
 test_pgp_LDFLAGS = 
 test_pgp_DEPENDENCIES = $(DEPS)
 test_pgp_LDADD = $(LDADDS)
 
-test_pgpmime_SOURCES = test-pgpmime.c
+test_pgpmime_SOURCES = test-pgpmime.c testsuite.c testsuite.h
 test_pgpmime_LDFLAGS = 
 test_pgpmime_DEPENDENCIES = $(DEPS)
 test_pgpmime_LDADD = $(LDADDS)
 
 EXTRA_DIST = test1.eml test2.eml test3.eml
 
-check-local: tests
+VERBOSITY=-v
 
-testall : tests
-
-tests: MIMEtests PARSERtests STREAMtests CATtests FILTERtests ICONVtests PGPtests
-
-MIMEtests : test-mime
-	@echo "##"
-	@echo "## MIME regression tests"
-	@echo "##"
-
-PARSERtests : test-parser test-mbox test-partial
-	@echo "##"
-	@echo "## MIME Parser regression tests"
-	@echo "##"
-
-STREAMtests : test-streams
-	@echo "##"
-	@echo "## Stream regression tests"
-	@echo "##"
-
-CATtests : test-cat
-	@echo "##"
-	@echo "## StreamCat regression tests"
-	@echo "##"
-
-FILTERtests : test-html
-	@echo "##"
-	@echo "## Filter regression tests"
-	@echo "##"
-
-ICONVtests : test-iconv
-	@echo "##"
-	@echo "## iconv cache regression tests"
-	@echo "##"
-
-PGPtests : test-pgp test-pgpmime
-	@echo "##"
-	@echo "## PGP tests"
-	@echo "##"
+check-local: $(AUTOMATED_TESTS)
+	failed_tests=""; \
+	failed=0; \
+	passed=0; \
+ \
+	for test in $(AUTOMATED_TESTS); do \
+		testdir="$(srcdir)/data/`echo $${test} | sed -e 's/test-//'`"; \
+		if [ -d "$${testdir}" ]; then \
+			./$${test} $(VERBOSITY) $${testdir}; \
+			if [ $$? -ne 0 ]; then \
+				failed_tests="$${failed_tests}\n $${test}"; \
+				failed=`expr $${failed} + 1`; \
+			else \
+				passed=`expr $${passed} + 1`; \
+			fi; \
+		else \
+			./$${test} $(VERBOSITY) $(srcdir); \
+			if [ $$? -ne 0 ]; then \
+				failed_tests="$${failed_tests}\n $${test}"; \
+				failed=`expr $${failed} + 1`; \
+			else \
+				passed=`expr $${passed} + 1`; \
+			fi; \
+		fi \
+	done; \
+ \
+	echo "Results: $${passed} tests passed; $${failed} tests failed."; \
+	if [ $${failed} -ne 0 ]; then \
+		echo -e "Failed tests: $${failed_tests}"; \
+	fi
